apiVersion: apps/v1
kind: Deployment
metadata:
  name: steg-loto-backend
  labels:
    app: steg-loto-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: steg-loto-backend
  template:
    metadata:
      labels:
        app: steg-loto-backend
    spec:
      containers:
      - name: backend
        image: steg-loto-backend:1.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/loto_db
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: steg-loto-backend-service
spec:
  selector:
    app: steg-loto-backend
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cm9vdA==      # root (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  uri: bW9uZ29kYitzcnY6Ly9mZWRpbWVjaGVyZ3VpMDM6SUdSQjF3OEdlYlVORGRNWEBjbHVzdGVyMC55dnJzZ2xoLm1vbmdvZGIubmV0L3N0ZWdfbG90bz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
